name: crystal
version: '0.24.2+git' 
summary: Fast as C, slick like Ruby
description: |
  Crystal is a programming language with the following goals:
  - Have a syntax similar to Ruby (but compatibility with it is not a goal)
  - Statically type-checked but without having to specify
  the type of variables or method arguments.
  - Be able to call C code by writing bindings to it in Crystal.
  - Have compile-time evaluation and generation of code,
  to avoid boilerplate code.
  - Compile to efficient native code.

grade: devel
confinement: devmode

parts:
  bcw-gc:
    plugin: autotools
    prepare: |
      autoreconf -vif
    source: https://github.com/ivmai/bdwgc.git
    
  crystal-runtime:
    plugin: dump
    source: https://github.com/crystal-lang/crystal/releases/download/0.24.2/crystal-0.24.2-1-linux-x86_64.tar.gz
    
  crystal-src:
    after: [ bcw-gc, crystal-runtime ]
    plugin: nil
    source: https://github.com/crystal-lang/crystal.git
    install: |
      make
    build-packages:
      - git
      - build-essential
      - pkg-config
      - llvm-3.9
      - libpcre3-dev
      - libevent-dev
      - libssl-dev
    
    stage-packages:
      - libreadline-dev
      - libgmp-dev
      - libyaml-dev
      - libz-dev
      - libxml2-dev
      - libgc-dev  
       
apps:
  crystal:
    command: bin/crystal
    plugs:
      - home
      - network
      - network-observe
 
